
#======================================
# THIS FILE IS AUTOMATICALLY GENERATED
# See util/generate-tests.py
#======================================

from twisted.trial.unittest import TestCase
from parsefin.test.util import testFile


class TestFiles(TestCase):


    def test_1_input_ofx(self):
        """
        data/1.input.ofx -> data/1.output.json
        """
        testFile(self, 'data/1.input.ofx', 'data/1.output.json')


    def test_2_input_qfx(self):
        """
        data/2.input.qfx -> data/2.output.json
        """
        testFile(self, 'data/2.input.qfx', 'data/2.output.json')


    def test_3_input_ofx(self):
        """
        data/3.input.ofx -> data/3.output.json
        """
        testFile(self, 'data/3.input.ofx', 'data/3.output.json')

