language: python
python: 2.7

env:
    - TOX_ENV=pyflakes
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy

install:
    - pip install -U pip
    - pip install -r dev-requirements.txt

before_script:
    - make generate

script: tox -e $TOX_ENV
