#!/usr/bin/env python
# Copyright (c) Matt Haggard.
# See LICENSE for details.

import sys
from parsefin import parseFile
from parsefin.general import toJson
fh = open(sys.argv[1], 'rb')
sys.stdout.write(toJson(parseFile(fh), indent=2) + '\n')
